name: Delete Branch on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        run: echo "PR state ${{ github.event.pull_request.merged }}"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Delete branch
        if: github.head.ref == 'update/applications'
        run: |
          git fetch --all --prune
          git branch -D 'update/applications'
