on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited applications.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate applications.json schema
        run: jsonschema -i applications.json ./applications.schema.json;
